#
# Copyright (C) Red Gate Software Ltd 2010-2021
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#         http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

version: 2.1

orbs:
  maven: circleci/maven@1.2.0

jobs:
  maven_build:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - checkout
      - maven/with_cache:
          verify_dependencies: false
          steps:
            - run:
                command: mvn  -e -U clean compile install -T1C -DskipTests -DskipITs -Pbuild-assemblies
  maven_test:
    docker:
      - image: cimg/openjdk:11.0
    steps:
      - maven/with_cache:
          verify_dependencies: false
          steps:
            - run:
                command: mvn -e -U jacoco:prepare-agent@PrepareAgent surefire:test jacoco:report@ReportSmallTests -Pbuild-assemblies
      - run:
          name: Save test results
          command: |
            mkdir -p ~/test-results/junit/
            find . -type f -regex "../flyway-enterprise/*/target/surefire-reports/.*xml" -exec cp {} ~/test-results/junit/ \;
          when: always
      - store_test_results:
          path: ~/test-results
workflows:
  flyway_build:
    jobs:
      - maven_build
      - maven_test:
          requires:
            - maven_build